### ISSUE TITLE
Animation with precomp shows hidden elements

### ISSUE THREAD

**Issue by julienbodet** [airbnb/lottie-ios#861]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
I run an animation having a precomp that doesn't look the same on 2.5.3 and 3.0.x. It should look the same. Here is how it looks on 2.5.3:

![no_bug](https://user-images.githubusercontent.com/3465275/56079801-3294d300-5dc7-11e9-8120-9de85ad6e6d9.gif)

## Actual Behavior
Some parts of the animation that should be hidden are actually shown on 3.0.x versions. Here is how it looks on 3.0.4:

![bug](https://user-images.githubusercontent.com/3465275/56079802-3a547780-5dc7-11e9-8eab-4ec13237bfe8.gif)

## Animation JSON
I sent it to brandon@withrow.io

Thanks for your help :)

**Comment by JoeSzymanski** [comment]
This might have been fixed by the changes in #873 which touched upon handling of hidden layers, I think.

**Comment by julienbodet** [comment]
@JoeSzymanski Thanks for letting me know. I'll test it and close the issue if it is the resolved.

**Comment by julienbodet** [comment]
I pulled master and unfortunately it's not working with this new fix.

**Comment by JoeSzymanski** [comment]
Was worth checking. Hopefully these issues can all be resolved soon.

**Comment by buba447** [comment]
Fixed!

**Comment by julienbodet** [comment]
Thanks for the update @buba447!

**Comment by julienbodet** [comment]
@buba447 I tested with 3.1.5 and I still see the bug. Is the fix released?

**Comment by julienbodet** [comment]
@buba447 I tested by pointing to 3.1.5 and last commit of master and I still see the bug.

**Comment by buba447** [comment]
@julienbodet The fix is on master. Be sure to clean (CMD+K) after changing versions of Lottie or you will not be building the new code.

Heres a screenshot of your animation using the latest master:

<img width="380" alt="Screen Shot 2019-11-29 at 10 01 08 AM" src="https://user-images.githubusercontent.com/1163980/69880336-53933100-128f-11ea-93ab-8e8bf7663aa2.png">

Cheers!

**Comment by julienbodet** [comment]
@buba447 Oh, I forgot to clean. It works now, thanks! I'm curious is [that](https://github.com/airbnb/lottie-ios/pull/1087) the fix?
